Handle anonymous user tokens in `symfony` < `6.x`
worldia/instrumentation-bundle pull request #10
Opened 2022-08-24 17:30 UTC by BowlingX

Thank you first for this bundle!

This PR adds support for older symfony versions (particular `< 6`).

The current implementation throws an error when accessing `getRoles()` on a `string`.
So I adjusted it to check before pulling them (similar what `getUsername` was already doing)

I further added (basic) tests for the user instrumentation. To make tests easier I introduced a new interface `MainSpanContextInterface`.

In general compatibility of this bundle is unclear as it's always pulling in the latest symfony version and there is no`composer.lock` file (worth another PR?), but as symfony `5.4` is the latest lts I think it would make sense to support that.

2022-08-24 19:39 UTC, cdaguerre commented
Good job! Could you just fix the failing phpstan tests?

2022-08-24 20:52 UTC, BowlingX commented
Thank you :) great, I made the adjustments.

2022-08-25 12:48 UTC, camilledejoye requested changes
Just two types to fix so that we properly handle Symfony 5 :)

2022-08-25 12:48 UTC, camilledejoye commented on src/Tracing/Instrumentation/EventSubscriber/AddUserEventSubscriber.php
> +    private function getUsername(UserInterface|string $user): ?string
Same here:
```suggestion
    private function getUsername(UserInterface|\Stringable|string $user): ?string
```

2022-08-25 12:48 UTC, camilledejoye commented on src/Tracing/Instrumentation/EventSubscriber/AddUserEventSubscriber.php
> +    private function getRoles(UserInterface|string $user): array
To properly handle [Symfony 5](https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/Security/Core/Authentication/Token/TokenInterface.php#L54):
```suggestion
    private function getRoles(UserInterface|\Stringable|string $user): array
```

2022-08-25 14:07 UTC, merged

2022-08-25 14:09 UTC, cdaguerre commented
thanks @BowlingX