fix: do no resolve route a second time and use REQUEST_URI to trace the request path
worldia/instrumentation-bundle pull request #12
Opened 2022-10-22 14:16 UTC by cyve

Reduce execution time by avoiding to resolve the controller a second time to get the route path (-10ms in prod mode on my machine).

Consequences :
- The trace title displayed in jaeger is now the resolved path instead of the pattern (ex: `/rooms/{method}` => `/rooms/find`)
- The `http_route` attribute is no longer present (but we still have the complete URL and controller name in the attributes)

I also remove the test `it_does_not_update_server_span_when_controller_is_resolved_for_main_request_with_unknown_route`. It is useless because the event `kernel.controller` will never be dispatched if the controller is not resolved.

2022-10-22 15:50 UTC, camilledejoye commented
> Reduce execution time by avoiding to resolve the controller a second time to get the route path (-10ms in prod mode on my machine).

We don't actually "resolve the controller" anywhere in this class.
What leads you to conclude the slowness you experienced came from there ?  
Can we have a link to a profiling result of some sort ?

At first glance it seems unlikely that `$this->router->getRouteCollection()->get($routeAlias)` will resolve anything.  
The collection should already been build by now so there is no extra cost (not mentioning it's cached).
Then retrieving the route is simply accessing an element from an array (except if you use route aliases but even then the cost should be neglectable.

> The trace title displayed in jaeger is now the resolved path instead of the pattern (ex: /rooms/{method} => /rooms/find)

That would be a big nono because there is a will to follow the [Semantic conventions for HTTP spans](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#name).

> The http_route attribute is no longer present (but we still have the complete URL and controller name in the attributes)

That also breaks some requirements from the [HTTP Server semantic conventions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#http-server-semantic-conventions), specifically:

> http.route MUST be provided at span creation time if and only if it’s already available. If it becomes available after span starts, instrumentation MUST populate it anytime before span ends.

> I also remove the test it_does_not_update_server_span_when_controller_is_resolved_for_main_request_with_unknown_route. It is useless because the event kernel.controller will never be dispatched if the controller is not resolved.

I suppose it depends, if you assume everyone will always use the exact same `HttpKernel` with the exact same behavior and that this behavior is part of the same unit you're currently tested then I guess we could consider it useless.
On the other hand if you think of a unit test goal as being to shield you against possible miss usage of something you have no control over I would advocate that adding a 10 lines test which does not take a milli-second to execute is not that harmful.
IMO it's ill-advised when distributing a library to build our tests based on assumptions about how it will be used by the end-user.

Still, I realized the tests were not "realistic" in the sense that we resolve the test's route template as `/test/{id}` while we create a request event for `/test` instead of something like `/test/53`.
Because of that, if the proposed changes should been accepted the tests won't be good examples of the behavior of the class since they are lie.
We should fix that when we'll have the opportunity.

2022-10-23 11:51 UTC, cyve commented
> That would be a big nono because there is a will to follow the [Semantic conventions for HTTP spans](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/http/#name).

I agree with you about the naming, I wasn't aware of the conventions. I propose another way to retrieve the original path pattern without performance issues.

2022-10-23 12:15 UTC, cyve commented
> At first glance it seems unlikely that $this->router->getRouteCollection()->get($routeAlias) will resolve anything.
The collection should already been build by now so there is no extra cost (not mentioning it's cached).

Sorry, my comment what not very clear. Using `getRouteCollection()` will regenerate the entire cache for the routing component. As it is said [here](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Routing/RouterInterface.php) and [here](https://symfony.com/doc/current/routing#checking-if-a-route-exists), we should never use it at runtime.

Retrieving the route directly from the cache is reducing the execution time by 20ms (67ms => 47ms) in dev mode on my machine (see screenshot below).
![instrumentation-profiler](https://user-images.githubusercontent.com/3588995/197390710-02d764c4-9ee7-4c80-acf5-e1496c306198.jpg)

In prod mode with opcache enabled (still on my machine), the execution time is reduced by 11ms (46ms => 35ms)
```
$ ab -n 100 -m POST https://api.worldia.loc/rooms/find

# before
Requests per second:    21.32 [#/sec] (mean)
Time per request:       46.906 [ms] (mean)
Time per request:       46.906 [ms] (mean, across all concurrent requests)

# after
Requests per second:    28.31 [#/sec] (mean)
Time per request:       35.322 [ms] (mean)
Time per request:       35.322 [ms] (mean, across all concurrent requests)
```

I also tried it on the preprod of one of my side project's and the result is quite the same (~10ms).

10ms might seems very small. But my project has an average execution time of 50-100ms. So +10ms is up to +20% (just to add an attribute on a trace).

An alternative solution should be to add our own [cache warmer](https://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer) to store the informations we need in our own cache file (or apcu or redis)

2022-10-23 14:22 UTC, camilledejoye commented
Thanks, a lot clearer!

> An alternative solution would be to add our own [cache warmer](https://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer) to store the informations we need in our own cache file (or apcu or redis)

I agree, it would be best. Otherwise the subscriber has too many responsibility. In case of a change in the name of the cached file, in the structure of the compiled routes, etc. We will need to change this subscriber.  
So having a dedicated service to do this "route path resolution" would avoid breaking SRP while providing the availability to add any caching we might want.
The tests will therefore be a lot easier to write and one could even decorate this new service in case of need in its own application.

2022-10-24 09:21 UTC, cdaguerre commented
Thanks a lot for this PR, this is indeed a real performance impact.
The operation name is not only about semantic conventions. In real life, having distinct operation names for every variation of route parameters makes no sense, so we have have low cardinality for operation names. For the sake of completeness, for the `http.route`, in addition to 

> `http.route` MUST be provided at span creation time if and only if it’s already available. If it becomes available after span starts, instrumentation MUST populate it anytime before span ends.

the semantic conventions of OpenTelemetry also state : 

> `http.route` MUST NOT be populated when this is not supported by the HTTP server framework as the route attribute should have low-cardinality and the URI path can NOT substitute it.  

It is arguable whether this is actually supported by symfony or not. What we could do quite easily is use the route name (`_route` request attribute), but it's not in the form of regular http path like `/some/route/{param}` but rather `some_route`.

I see a variety of solutions:
- use the `_route` request attribute
- use an `operation_name` attribute the user manually defines route per route (fallback to something else if it doesn't exist)
- implement a `_route` to `path` map (the cache warmer approach mentioned earlier)
- tweak symfony's url matcher dumper to always include the `_path` attribute, eg like this https://github.com/symfony/symfony/pull/47970

2022-10-24 09:25 UTC, cdaguerre commented
also, these attributes should be set ASAP, just after the RouterListener added request attributes (KernelEvents::REQUEST, priority < 32).

2022-10-26 12:53 UTC, cdaguerre requested changes

2022-10-26 12:53 UTC, cdaguerre commented on src/Routing/RoutePathResolver.php
> +        private ?string $cacheDir = null,
this should not be nullable

2022-10-26 13:18 UTC, cdaguerre approved these changes

2022-10-26 13:19 UTC, merged

2022-10-31 12:29 UTC, jderusse commented on src/Routing/RoutePathResolver.php
> +            return $this->router->getRouteCollection()->get($routeName)?->getPath();
The comment does not tell what the code does: The current implementation does not warm the cache.