fix: TracingHttpClient span duration
worldia/instrumentation-bundle pull request #32
Opened 2022-12-01 15:31 UTC by cyve

The current issue : 
The TracingHttpClient [on_request](https://github.com/worldia/instrumentation-bundle/blob/master/src/Http/TracingHttpClient.php#L68) callable set the "status_code" attribute as soon as the client receive the status code from the server. But it also ends the span at the same time. So the span does not include the content download time. For example, if the server responds in 200ms, but it takes 1s to download the content. The client will receive the status code after 200ms, and the span will have a duration of 200ms instead of 1.2s.

This PR adds : 
- Class TracedResponse that will end the span after the content is fully downloaded.
- static boolean `$dlStarted` in the "on_progress" callback to avoid adding attributes twice
- `int $maxHostConnections` and `int $maxPendingPushes` to constructor argument to match with `HttpClient::create()` signature.

Before :
<img width="388" alt="before" src="https://user-images.githubusercontent.com/3588995/205093055-9a38ac10-0b4e-438e-ac0d-8f8f37859c2d.png">
After : 
<img width="372" alt="after" src="https://user-images.githubusercontent.com/3588995/205093051-be8dba57-9150-4f5e-a08e-9b1f7fb8d389.png">

2022-12-01 15:40 UTC, cyve commented
@cdaguerre The phpspec tests failed, but they also fail on the master branch... :-/

2023-01-10 14:55 UTC, cdaguerre requested changes

2023-01-10 14:55 UTC, cdaguerre commented on src/Http/TracedResponse.php
> +class TracedResponse implements ResponseInterface
Should implement `Symfony\Component\HttpClient\Response\StreamableInterface`, ref. https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/HttpClient/Response/TraceableResponse.php

2023-01-10 14:55 UTC, cdaguerre commented on src/Http/TracingHttpClient.php
> +        int $maxHostConnections = 6,
:+1:

2023-01-11 15:24 UTC, cdaguerre commented on src/Http/TracedResponse.php
> +        $this->span->end();
As discussed, this could end the span much later than expected in case of a long running script and so on. Unfortunately there is no guarantee that the end time of the request is available in the array returned by the decorated `$reponse->getInfo()` call so far. Ref. https://github.com/symfony/http-client-contracts/blob/c5f587eb445224ddfeb05b5ee703476742d730bf/ResponseInterface.php#L81

It seems however that several implementations include it, eg. Curl, Amp, Native (not HttpPlug apparently).
We could make sure it is always theres similarly to what is done here (passing $info by reference in `on_progress` callback: https://github.com/symfony/http-client/blob/6.2/Response/AmpResponse.php#L95
See suggestion below...
WDYT?

2023-01-11 15:26 UTC, cdaguerre commented on src/Http/TracingHttpClient.php
>              'on_progress' => function ($dlNow, $dlSize, $info) use ($onProgress, $span) {
```suggestion
            'on_progress' => function ($dlNow, $dlSize, &$info) use ($onProgress, $span) {
                $info['total_time'] = microtime(true) - $info['start_time'];
```

2023-01-11 18:13 UTC, cyve commented on src/Http/TracingHttpClient.php
>              'on_progress' => function ($dlNow, $dlSize, $info) use ($onProgress, $span) {
I left the `static $dlStarted` because it has no impact on the `total_time` update

2023-01-12 16:31 UTC, merged